### ISSUE TITLE
No data detected within 5 seconds error.

### ISSUE THREAD

**Issue by Cocome124** [HenkKalkwater/fitmetersync#17]
Every time i try to sync my fit meter with my New 2DS XL it says “ No data detected within 5 seconds.” The thing is, it spits out hex. Here it is if you need it: <- a5 00 84 01    
04 04 64 4b  
-> a5 0c 84 01     
04 04 4d 7f
Any help is very much appreciated!

**Comment by HenkKalkwater** [comment]
HI Cocome124,

thanks for your interest in this application! However, this application is not yet ready and it does nothing yet besides logging data to the bottom screen and `.PCAP` files on your SD card. This program will often respond wrongly to the Fit Meter because I simply was testing whether something works or not. Because of that, the Fit Meter stops responding and you will get the "No data detected within 5 seconds" message, to let you know that the program is not receiving any data over infrared any more. This is expected.

Since this program is a—still far from working—prototype and this behaviour is expected, I will close this issue. If it happens again after the first release of this program, you may create a new one :)

**Comment by HenkKalkwater** [comment]
I have updated the README to explicitly mention that this is a non-functional prototype
